<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-U1MUJFT" failures="1" tests="4" name="Test" time="27.283" errors="0" timestamp="2023-03-07T22:37:07 IST">
  <testcase classname="com.saucedemo.TestPack.TC03_VerifyBagProductAddToCartFunctionality" name="verifyBagProductAddToCartFunctionality" time="0.25"/>
  <testcase classname="com.saucedemo.TestPack.TC04_VerfiyAllProductsAddToCartFunctionality" name="verfiyAllProductsAddToCartFunctionality" time="0.441">
    <failure type="java.lang.AssertionError" message="expected [6] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [6] but found [3]
at com.saucedemo.TestPack.TC04_VerfiyAllProductsAddToCartFunctionality.verfiyAllProductsAddToCartFunctionality(TC04_VerfiyAllProductsAddToCartFunctionality.java:24)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verfiyAllProductsAddToCartFunctionality -->
  <testcase classname="com.saucedemo.TestPack.TC02_VerifyLogOutFunctionality" name="verifyLogOutFunctionality" time="0.526"/>
  <testcase classname="com.saucedemo.TestPack.TC01_VerifyLoginFunctionality" name="verifyLoginFunctionality" time="0.013"/>
</testsuite> <!-- Test -->
